### ISSUE TITLE
CMS updates won't deploy

### ISSUE THREAD

**Issue by Discocowboy** [DSCoalition/dsc-11ty-cms#98]
There is an issue again when deploying updates through the CMS
![Screenshot 2024-02-14 at 1 33 36 PM](https://github.com/DSCoalition/dsc-11ty-cms/assets/12417007/546dec2d-6ed7-4a11-ae62-4e846e2fe0ce)

**Comment by SeaJerry** [comment]
This GitHub Action error can safely be ignored. This error is thrown because we did not remove the deprecated GitHub Action Workflow. Therefore, the site was still being deployed via GitHub Pages. The GitHub Actions Workflow has been removed from the repo, and the site is currently hosted through Cloudflare Pages.
